from typing import TypedDict, Annotated, List
import operator

class AgentState(TypedDict):
    """
    Represents the state of the Mantiq-AI orchestration graph.
    This state is passed between different nodes (agents) in the cyclic workflow.
    """
    
    # The initial task or objective provided by the user
    task: str
    
    # A collection of findings or documents gathered by the Researcher Agent
    # Annotated with operator.add if you want to append data incrementally 
    research_data: Annotated[List[str], operator.add]
    
    # The latest version of the content generated by the Writer Agent
    draft: str
    
    # Constructive feedback or rejection reasons provided by the Reviewer Agent
    feedback: str
    
    # Counter to track iterations and prevent infinite loops in the cyclic workflow
    revision_count: int
    
    # Metadata to track which agent was the last to modify the state
    next_step: str