import os
from datetime import datetime
import pdfkit
from src.core.state import AgentState
from src.database.db_manager import db  # Import the new DB manager

def saver_node(state: AgentState):
    """
    Saver Node: 
    1. Generates a professional PDF with RTL (Arabic) support.
    2. Archives the task metadata into the SQLite Long-Term Memory.
    """
    report_content = state.get("draft", "")
    task_name = state.get("task", "Mantiq-AI Report")
    selected_model = state.get("selected_model", "unknown")
    
    output_dir = "outputs"
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
    
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"{output_dir}/report_{timestamp}.pdf"
    
    print(f"\n--- 💾 LOG: Saver Node Active ---")
    print(f"--- 📄 LOG: Generating Web-Standard PDF for: {task_name} ---")

    # --- PART 1: ARCHIVE TO SQLITE (Long-Term Memory) ---
    try:
        db.log_task_completion(task_description=task_name, model_used=selected_model)
    except Exception as db_err:
        print(f"--- ⚠️ WARNING: Database archiving failed: {db_err} ---")

    # --- PART 2: PDF GENERATION (HTML-to-PDF Strategy) ---
    # Using HTML/CSS is the most reliable way to handle Arabic fonts and RTL layout
    html_template = f"""
    <!DOCTYPE html>
    <html dir="rtl" lang="ar">
    <head>
        <meta charset="UTF-8">
        <style>
            body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; padding: 40px; line-height: 1.6; color: #333; }}
            h1 {{ color: #1a5f7a; text-align: center; border-bottom: 2px solid #1a5f7a; padding-bottom: 10px; }}
            .metadata {{ font-size: 12px; color: #666; text-align: left; margin-bottom: 20px; direction: ltr; }}
            pre {{ white-space: pre-wrap; font-family: inherit; font-size: 14px; background: #f9f9f9; padding: 15px; border-radius: 5px; }}
            .footer {{ margin-top: 30px; text-align: center; font-size: 10px; color: #aaa; border-top: 1px solid #eee; padding-top: 10px; }}
        </style>
    </head>
    <body>
        <div class="metadata">Generated by Mantiq-AI | Model: {selected_model.upper()} | {datetime.now().strftime('%Y-%m-%d %H:%M')}</div>
        <h1>{task_name}</h1>
        <pre>{report_content}</pre>
        <div class="footer">Confidential Enterprise Report - Powered by Hybrid RAG Engine</div>
    </body>
    </html>
    """

    try:
        # PDFKit options for high-fidelity conversion
        options = {
            'encoding': "UTF-8",
            'quiet': '',
            'margin-top': '0.75in',
            'margin-right': '0.75in',
            'margin-bottom': '0.75in',
            'margin-left': '0.75in',
        }
        
        # Convert string to PDF
        pdfkit.from_string(html_template, filename, options=options)
        print(f"--- ✅ SUCCESS: PDF saved to {filename} ---")
        return {"next_step": "FINISH"}

    except Exception as e:
        print(f"--- ❌ ERROR: PDF Generation failed: {str(e)} ---")
        
        # Reliable Fallback: Save as Markdown if PDF engine (wkhtmltopdf) is missing
        fallback_file = filename.replace(".pdf", ".md")
        with open(fallback_file, "w", encoding="utf-8") as f:
            f.write(f"# {task_name}\n\n{report_content}")
        print(f"--- 💡 INFO: Falling back to Markdown: {fallback_file} ---")
        
        return {"next_step": "FINISH"}